export const SITE_OPTIONS = [
  "Angola - Huambo",
  "Argentina - Buenos Aires",
  "Brazil - Florianopolis",
  "Brazil - Joao Pessoa",
  "Brazil - Ponta Grossa",
  "Brazil - Rio de Janeiro",
  "Croatia - Zagreb",
  "Ecuador - Tabacundo",
  "Italy - Lecce",
  "Italy - Padova",
  "Italy - Vicenza",
  "Japan - Kasama",
  "Japan - Machida (Tokyo)",
  "Philippines",
  "Poland - Krakow",
  "Poland - Lodz",
  "Spain - Murcia Alcantarilla",
  "USA - Massachusetts - West Springfield",
];
