export const STAFF_TASK_TEMPLATE = [

    // 1. Team/Project Formation
    {
        id: "project-locked",
        workArea: "Project Formation",
        sequence: 1,
        taskName: "Project locked (apps approved, matched to site, dates set)",
        assignedTo: "Leslee",
        progress: "Not Started",
        dueDate: "",
        notes: "",
    },
    {
        id: "update-logistics-plan",
        workArea: "Project Formation",
        sequence: 1,
        taskName: "Update Project Logistics and Plan doc for this site",
        assignedTo: "Craig",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "lock-message-host",
        workArea: "Project Formation",
        sequence: 1,
        taskName: "Forward 'lock' message to host and team",
        assignedTo: "Craig",
        progress: "Not started",
        dueDate: "",
        notes: "Include link to Project Logistics and Plan doc, to LST Host general expectations, Team expectations, Recruiting Readers, and LST Hub",
    },
    {
        id: "add-project-docs",
        workArea: "Project Formation",
        sequence: 1,
        taskName: "Add project to internal record docs",
        assignedTo: "Craig",
        progress: "Not started",
        dueDate: "",
        notes: "1) stat doc, 2) team budget/travel doc",
    },
    {
        id: "add-project-cal",
        workArea: "Project Formation",
        sequence: 1,
        taskName: "Add project to internal/public calendars",
        assignedTo: "Craig",
        progress: "Not started",
        dueDate: "",
        notes: "1) outlook, 2) web, 3) LST master calendar (excel), and 3) update public site list on web",
    },
    {
        id: "create-neon-event",
        workArea: "Project Formation",
        sequence: 1,
        taskName: "Create Event in Neon and register site/workers (Master List)",
        assignedTo: "Donna",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "send-reference-requests",
        workArea: "Project Formation",
        sequence: 1,
        taskName: "Send out reference requests to the team",
        assignedTo: "Mackayla",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "social-media",
        workArea: "Project Formation",
        sequence: 3,
        taskName: "Create social media post to go out on week of their departure",
        assignedTo: "Hannah",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },

    //2. Fundraising
    {
        id: "create-neon-fundraising-page",
        workArea: "Fundraising",
        sequence: 1,
        taskName: "Fundraising deadlines set",
        assignedTo: "Donna",
        progress: "Not started",
        dueDate: "",
        notes: "Set $2,000 'due date' at 90 days, then at 30 days",
    },
    {
        id: "fundraising-deadlines",
        workArea: "Fundraising",
        sequence: 1,
        taskName: "Fundraising pages created and tied as 'teams' in Neon",
        assignedTo: "Donna",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "fundraising-links",
        workArea: "Fundraising",
        sequence: 1,
        taskName: "Add links to each person's fundraising page",
        assignedTo: "Donna",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },

    //3. Training
    {
        id: "training-launch",
        workArea: "Training",
        sequence: 2,
        taskName: "Trigger automated support email series [Neon workflow] for each team member",
        assignedTo: "Craig",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "training-launch-appt",
        workArea: "Training",
        sequence: 2,
        taskName: "Conduct 'Training Launch' appointment with each team within one week of locking",
        assignedTo: "Leslee",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "team-signed-up-training",
        workArea: "Training",
        sequence: 2,
        taskName: "Team signed up for training platform?",
        assignedTo: "Leslee",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "basic-training",
        workArea: "Training",
        sequence: 2,
        taskName: "Basic Training completed",
        assignedTo: "Craig",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "gateway-training",
        workArea: "Training",
        sequence: 2,
        taskName: "Gateway Training completed",
        assignedTo: "Craig",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "team-training",
        workArea: "Training",
        sequence: 2,
        taskName: "Primary Team Training completed",
        assignedTo: "Leslee",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },

    //4. Travel
    {
        id: "visa-entry-requirements",
        workArea: "Travel",
        sequence: 2,
        taskName: "Visa / other entry requirements sent to the team",
        assignedTo: "Craig",
        progress: "Not started",
        dueDate: "",
        notes: "#1-Send message to team early in process outlining what entry requirements there maybe (including expiration date of their passport. #2- For those with specific entry requirements follow up separately and help each team member get what's needed. Visas - Brazil. Passports - note what the site-country requires as far as passport validity (example = 3 months past date of departure FROM the country). Other - EU will require ETIAS starting 2025. South Korea - will require K-ETA starting 2025. Poland- Anyone working with minors needs an original police report if working one-to-one",
    },
    {
        id: "travel-form",
        workArea: "Travel",
        sequence: 2,
        taskName: "Travel Form completed by team",
        assignedTo: "Leslee",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "tickets-purchased",
        workArea: "Travel",
        sequence: 2,
        taskName: "Tickets purchased (record date)",
        assignedTo: "Leslee",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "tickets-sent",
        workArea: "Travel",
        sequence: 2,
        taskName: "Sent ticket details to team (record date)",
        assignedTo: "Leslee",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "tickets-sent-host",
        workArea: "Travel",
        sequence: 2,
        taskName: "Sent ticket details to host (record date)",
        assignedTo: "Craig",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "safety-email",
        workArea: "Travel",
        sequence: 2,
        taskName: "Send email to team about any saftey issues related to their site",
        assignedTo: "Craig",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "insurance-purchased",
        workArea: "Travel",
        sequence: 2,
        taskName: "Insurance purchased and sent to team (Faith Ventures; send e-card and proof of insurance letter)",
        assignedTo: "Craig",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },


    // 5. Site Prep
    {
        id: "housing-addressed",
        workArea: "Site Prep",
        sequence: 3,
        taskName: "Housing addressed",
        assignedTo: "Craig",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "worksite-arranged",
        workArea: "Site Prep",
        sequence: 3,
        taskName: "Worksite arranged",
        assignedTo: "Craig",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "airport-travel",
        workArea: "Site Prep",
        sequence: 3,
        taskName: "Travel to/from airport addressed",
        assignedTo: "Craig",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "recruiting-readers",
        workArea: "Site Prep",
        sequence: 3,
        taskName: "Recruiting Readers addressed (Remind Host about HUB)",
        assignedTo: "Craig",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "local-transportation",
        workArea: "Site Prep",
        sequence: 3,
        taskName: "Local transportation addressed",
        assignedTo: "Craig",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "comm-addressed",
        workArea: "Site Prep",
        sequence: 3,
        taskName: "Tel/Comm addressed",
        assignedTo: "Craig",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "project-scheduled",
        workArea: "Site Prep",
        sequence: 3,
        taskName: "Project schedule set",
        assignedTo: "Craig",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "one-month-check-in",
        workArea: "Site Prep",
        sequence: 3,
        taskName: "Logistical touchpoint one month before project",
        assignedTo: "Craig",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },

    // 6. Materials
    {
        id: "release-forms",
        workArea: "Materials",
        sequence: 3,
        taskName: "Release forms signed (PandaDoc)",
        assignedTo: "Craig",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "budget-created",
        workArea: "Materials",
        sequence: 3,
        taskName: "Budget created",
        assignedTo: "Leslee",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "money-sent",
        workArea: "Materials",
        sequence: 3,
        taskName: "Budget check/money sent",
        assignedTo: "Leslee",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "record-keeping",
        workArea: "Materials",
        sequence: 3,
        taskName: "Record-keeping tools (stats and accounting)",
        assignedTo: "Leslee",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "materials-sent",
        workArea: "Materials",
        sequence: 3,
        taskName: "Support materials (daily planner, project handbook, receipts, recruiting cards, t-shirts, etc.)",
        assignedTo: "Leslee",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "workbooks-sent",
        workArea: "Materials",
        sequence: 3,
        taskName: "Workbooks sent",
        assignedTo: "Leslee",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },

    // 7. Support During Project
    {
        id: "updates-from-team",
        workArea: "During Project",
        sequence: 3,
        taskName: "Regular update(s) from team",
        assignedTo: "Leslee",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "updates-from-site",
        workArea: "During Project",
        sequence: 3,
        taskName: "Regular update(s) from site",
        assignedTo: "Craig",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },

    // 8. Post Project
    {
        id: "post-project-email",
        workArea: "Post Project",
        sequence: 3,
        taskName: "Trigger post-project email series for returned Workers [Neon workflow]",
        assignedTo: "Craig",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "post-project-email-host",
        workArea: "Post Project",
        sequence: 3,
        taskName: "Trigger post-project email series for HOST (evaluation) [Neon Workflow]",
        assignedTo: "Craig",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "handwritten-note",
        workArea: "Post Project",
        sequence: 3,
        taskName: "Send handwritten thank you note to each Worker",
        assignedTo: "Craig",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "end-meeting",
        workArea: "Post Project",
        sequence: 3,
        taskName: "Team attended EndMeeting",
        assignedTo: "Craig",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "record-keeping",
        workArea: "Post Project",
        sequence: 3,
        taskName: "Record-keeping docs complete",
        assignedTo: "Craig",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "remaining-funds",
        workArea: "Post Project",
        sequence: 3,
        taskName: "Remaining funds returned",
        assignedTo: "Donna",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    ];
