export const STAFF_TASK_TEMPLATE = [
    {
        id: "project-locked",
        workArea: "Team/Project Formation",
        sequence: 1,
        taskName: "Project locked (apps approved, matched to site, dates set)",
        assignedTo: "Leslee",
        progress: "Not Started",
        dueDate: "",
        notes: "",
    },
    {
        id: "create-project-checklist",
        workArea: "Team/Project Formation",
        sequence: 1,
        taskName: "Create project management checklist (Excel)",
        assignedTo: "Craig",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "update-logistics-plan",
        workArea: "Team/Project Formation",
        sequence: 1,
        taskName: "Update Project Logistics and Plan doc for this site",
        assignedTo: "Craig",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "create-neon-fundraising-page",
        workArea: "Team Prep-Fundraising",
        sequence: 1,
        taskName: "Create Event in Neon and register site/workers",
        assignedTo: "Donna",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "fundraising-deadlines",
        workArea: "Team Prep-Fundraising",
        sequence: 1,
        taskName: "Fundraising deadlines set",
        assignedTo: "Donna",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "training-launch",
        workArea: "Team Prep-Training",
        sequence: 2,
        taskName: 'Conduct "Training Launch" appointment with each team within one week of locking',
        assignedTo: "Leslee",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "team-signed-up-training",
        workArea: "Team Prep-Training",
        sequence: 2,
        taskName: "Team signed up for training platform",
        assignedTo: "Leslee",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "visa-entry-requirements",
        workArea: "Team Prep-Travel",
        sequence: 2,
        taskName: "Visa / other entry requirements sent to the team",
        assignedTo: "Kelly and Craig",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "housing-addressed",
        workArea: "Site Prep",
        sequence: 3,
        taskName: "Housing addressed",
        assignedTo: "Craig",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "basic-training-complete",
        workArea: "Team Prep-Training",
        sequence: 3,
        taskName: "Basic Training completed",
        assignedTo: "Craig",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "gateway-training-complete",
        workArea: "Team Prep-Training",
        sequence: 3,
        taskName: "Gateway Training completed",
        assignedTo: "Craig",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "primary-training-complete",
        workArea: "Team Prep-Training",
        sequence: 3,
        taskName: "Primary Team Training completed",
        assignedTo: "Leslee",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "travel-form-completed",
        workArea: "Team Prep-Travel",
        sequence: 3,
        taskName: "Travel Form completed by team",
        assignedTo: "Leslee",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "tickets-purchased",
        workArea: "Team Prep-Travel",
        sequence: 3,
        taskName: "Tickets purchased (record date)",
        assignedTo: "Leslee",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "ticket-details-team",
        workArea: "Team Prep-Travel",
        sequence: 3,
        taskName: "Sent ticket details to team (record date)",
        assignedTo: "Leslee",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "ticket-details-host",
        workArea: "Team Prep-Travel",
        sequence: 3,
        taskName: "Sent ticket details to host (record date)",
        assignedTo: "Craig",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "insurance-sent",
        workArea: "Team Prep-Travel",
        sequence: 3,
        taskName: "Insurance purchased and sent to team",
        assignedTo: "Kelly and Craig",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "travel-airport-addressed",
        workArea: "Site Prep",
        sequence: 3,
        taskName: "Travel to/from airport addressed",
        assignedTo: "Craig",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "recruiting-readers-addressed",
        workArea: "Site Prep",
        sequence: 3,
        taskName: "Recruiting Readers addressed (remind host about HUB)",
        assignedTo: "Craig",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "local-transportation-addressed",
        workArea: "Site Prep",
        sequence: 3,
        taskName: "Local transportation addressed",
        assignedTo: "Craig",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "tel-comm-addressed",
        workArea: "Site Prep",
        sequence: 3,
        taskName: "Tel/Comm addressed",
        assignedTo: "Craig",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "project-schedule-set",
        workArea: "Site Prep",
        sequence: 3,
        taskName: "Project schedule set",
        assignedTo: "Craig",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "logistical-touchpoint",
        workArea: "Site Prep",
        sequence: 3,
        taskName: "Logistical touchpoint one month before project",
        assignedTo: "Craig",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "release-forms-signed",
        workArea: "Team Prep-Materials",
        sequence: 3,
        taskName: "Release forms signed (PandaDoc)",
        assignedTo: "Kelly and Craig",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "budget-created",
        workArea: "Team Prep-Materials",
        sequence: 3,
        taskName: "Budget created",
        assignedTo: "Leslee",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "budget-check-sent",
        workArea: "Team Prep-Materials",
        sequence: 3,
        taskName: "Budget check/money sent",
        assignedTo: "Leslee",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "record-keeping-tools",
        workArea: "Team Prep-Materials",
        sequence: 3,
        taskName: "Record-keeping tools (stats and accounting)",
        assignedTo: "Leslee",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "support-materials",
        workArea: "Team Prep-Materials",
        sequence: 3,
        taskName: "Support materials (daily planner, handbook, receipts, recruiting cards, t-shirts, etc.)",
        assignedTo: "Leslee",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "workbooks-sent",
        workArea: "Team Prep-Materials",
        sequence: 3,
        taskName: "Workbooks sent",
        assignedTo: "Leslee",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "regular-updates-team",
        workArea: "Support During Project",
        sequence: 4,
        taskName: "Regular update(s) from team",
        assignedTo: "Leslee",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "regular-updates-site",
        workArea: "Support During Project",
        sequence: 4,
        taskName: "Regular update(s) from site",
        assignedTo: "Craig",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "post-project-worker-series",
        workArea: "Post Project",
        sequence: 5,
        taskName: "Trigger post-project email series for returned workers",
        assignedTo: "Kelly",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "post-project-host-series",
        workArea: "Post Project",
        sequence: 5,
        taskName: "Trigger post-project email series for HOST (evaluation)",
        assignedTo: "Kelly",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "handwritten-thank-you",
        workArea: "Post Project",
        sequence: 5,
        taskName: "Send handwritten thank you note to each worker",
        assignedTo: "Kelly and Craig",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "team-attended-endmeeting",
        workArea: "Post Project",
        sequence: 5,
        taskName: "Team attended EndMeeting",
        assignedTo: "Craig",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "record-keeping-complete",
        workArea: "Post Project",
        sequence: 5,
        taskName: "Record-keeping docs complete",
        assignedTo: "Craig",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "remaining-funds-returned",
        workArea: "Post Project",
        sequence: 5,
        taskName: "Remaining funds returned",
        assignedTo: "Donna",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    {
        id: "export-plan-save-365",
        workArea: "Post Project",
        sequence: 5,
        taskName: "Export this plan and save in 365",
        assignedTo: "Craig",
        progress: "Not started",
        dueDate: "",
        notes: "",
    },
    ];