export const WORKER_TASK_TEMPLATE = [
  {
    id: "worker-task-application",
    title: "Fill out LST application",
    category: "worker_default",
    dueDaysBeforeStart: 162,
  },
  {
    id: "worker-task-training-platform",
    title: "Has access to training platform and has started training",
    category: "worker_default",
    dueDaysBeforeStart: 42,
  },
  {
    id: "worker-task-passport",
    title: "Has passport good for 3-6 months after end of LST Project",
    category: "worker_default",
    dueDaysBeforeStart: 33,
  },
  {
    id: "worker-task-visa",
    title: "Has visa or other entry requirements",
    category: "worker_default",
    dueDaysBeforeStart: 23,
  },
  {
    id: "worker-task-fundraising-2000",
    title: "Fundraising: $2,000 raised",
    category: "worker_default",
    dueDaysBeforeStart: 21,
  },
  {
    id: "worker-task-fundraising-all",
    title: "Fundraising: All raised",
    category: "worker_default",
    dueDaysBeforeStart: 21,
  },
  {
    id: "worker-task-thank-donors",
    title: "Fundraising: Thank you to donors",
    category: "worker_default",
    dueDaysBeforeStart: 21,
  },
  {
    id: "worker-task-checklist",
    title: "Received and has reviewed Project Management Checklist",
    category: "worker_default",
    dueDaysBeforeStart: 21,
  },
  {
    id: "worker-task-host-intro",
    title: "Our team has introduced ourselves to our Host (via Zoom, WhatsApp, email, etc.)",
    category: "worker_default",
    dueDaysBeforeStart: 21,
  },
  {
    id: "worker-task-ticketing-info",
    title: "Travel: Provided info LST needs for ticketing",
    category: "worker_default",
    dueDaysBeforeStart: 21,
  },
  {
    id: "worker-task-tickets",
    title: "Travel: Received my tickets",
    category: "worker_default",
    dueDaysBeforeStart: 21,
  },
  {
    id: "worker-task-waiver",
    title: "Signed LST Waiver",
    category: "worker_default",
    dueDaysBeforeStart: 21,
  },
  {
    id: "worker-task-step",
    title: "Signed up to STEP (U.S. Dept. of State)",
    category: "worker_default",
    dueDaysBeforeStart: 21,
  },
  {
    id: "worker-task-training-complete",
    title: "Completed all LST Training",
    category: "worker_default",
    dueDaysBeforeStart: 21,
  },
];
